import 'package:floor/floor.dart';
import 'package:habit_quest/database/entities/habit.dart';

/// A record of a habit for a specific date
@Entity(
  tableName: 'HabitRecord',
  foreignKeys: [
    ForeignKey(
      childColumns: ['habitId'],
      parentColumns: ['id'],
      entity: Habit,
      onDelete: ForeignKeyAction.cascade,
    ),
  ],
)
class HabitRecord {
  /// The unique ID of the habit record
  @PrimaryKey(autoGenerate: true)
  final int? id;

  /// The ID of the habit this record is associated with
  final int habitId;

  /// The date of the habit record
  final int date;

  /// The change in score for this habit record
  final int scoreDelta;

  HabitRecord({
    required this.habitId,
    required this.date,
    required this.scoreDelta,
  })  : id = null; // id will be auto-generated by the database
}